package com.ben.filamentmeter.vision

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import androidx.activity.compose.setContent
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.dp
import androidx.test.core.app.ActivityScenario
import androidx.test.platform.app.InstrumentationRegistry
import com.ben.filamentmeter.MainActivity
import com.ben.filamentmeter.ui.DetectionOverlay
import org.junit.Assert.*
import org.junit.Test
import java.io.File

class DetectionOverlayRenderTest {
    @Test fun referenceDetectionRendersOnCameraImage() {
        val instrumentation=InstrumentationRegistry.getInstrumentation()
        val original=instrumentation.context.assets.open("reference-spaghetti.png").use { BitmapFactory.decodeStream(it) }
        val photo=Bitmap.createBitmap(original,975,23,original.width-975,665)
        val boxes=YoloFailureDetector(instrumentation.targetContext).use { it.detect(photo,.7f) }
        assertTrue(boxes.any { it.kind==1 })
        ActivityScenario.launch(MainActivity::class.java).use { scenario ->
            scenario.onActivity { activity -> activity.setContent {
                MaterialTheme {
                    Surface { Column(Modifier.fillMaxSize().padding(28.dp)) {
                        Text("OVERLAY TEST · reference image, not live camera")
                        Box(Modifier.fillMaxWidth().aspectRatio(1.35f)) {
                            Image(photo.asImageBitmap(),"Reference photo",Modifier.fillMaxSize(),contentScale=ContentScale.Fit)
                            DetectionOverlay(boxes,photo.width,photo.height,true,1f,Modifier.matchParentSize())
                        }
                    } }
                }
            } }
            instrumentation.waitForIdleSync()
            android.os.SystemClock.sleep(700)
            val screenshot=instrumentation.uiAutomation.takeScreenshot()
            assertNotNull(screenshot)
            File(instrumentation.targetContext.filesDir,"overlay-test.png").outputStream().use {
                screenshot.compress(Bitmap.CompressFormat.PNG,100,it)
            }
            // Orange annotation pixels are generated by the overlay, not by the neutral reference scene.
            var marked=0
            for(y in 0 until screenshot.height step 2) for(x in 0 until screenshot.width step 2) {
                val c=screenshot.getPixel(x,y)
                if(android.graphics.Color.red(c)>240 && android.graphics.Color.green(c) in 160..185 && android.graphics.Color.blue(c) in 50..80) marked++
            }
            assertTrue("Detection outline must appear on screen",marked>100)
            screenshot.recycle()
        }
    }
}
